import { FileOperation } from './generationTypes';

export class ArtifactAssembler {
  public assemble(ops: FileOperation[]): { path: string; content: string; operation: string }[] {
    return ops.map(op => {
      let content = '';
      if (op.operation === 'create' || op.operation === 'modify') {
        content = `/**
 * Generated by Multi-file Generation Engine
 * Target: ${op.filePath}
 * Operation: ${op.operation}
 */
export const featureName = '${op.filePath.split('/').pop()?.split('.')[0]}';
`;
      }

      return {
        path: op.filePath,
        content,
        operation: op.operation
      };
    });
  }
}

export const artifactAssembler = new ArtifactAssembler();
