export enum ApprovalAction {
  CREATE_FILE = 'CREATE_FILE',
  UPDATE_FILE = 'UPDATE_FILE',
  DELETE_FILE = 'DELETE_FILE',
  MOVE_FILE = 'MOVE_FILE',
  RENAME_FILE = 'RENAME_FILE',
  RUN_TERMINAL = 'RUN_TERMINAL',
  INSTALL_PACKAGE = 'INSTALL_PACKAGE',
  MODIFY_CONFIGURATION = 'MODIFY_CONFIGURATION',
  UNKNOWN = 'UNKNOWN'
}
