import { aiKernel } from '../ai-kernel';
import { PlanningSessionBuilder } from '../planning-session-builder';
import { PlanningModelIntegration } from '../planning-model-integration';
import { PlanningValidatorHandoff } from '../planning-validator-handoff';
import { PipelineState, IPipelineEvent, IPipelineResult } from './types';
import { pipelineEventBus } from './event-bus';
import { IPlanningModelProvider } from '../planning-model-integration/types';
import { codeGenerationPipeline } from '../code-generation-pipeline';
import { workspacePipelineFacade } from '../workspace-pipeline-integrator';
import { IFilesystemAdapter, NodeFsAdapter } from '../workspace-engine/fs-adapter';
import { ICodingModelProvider } from '../coding-runtime/types';
import { OllamaPlanningProviderAdapter, OllamaCodingProviderAdapter, providerRegistry, OllamaProvider } from '../inference';
import * as crypto from 'crypto';

export class PipelineController {
  private state: PipelineState = 'IDLE';
  private currentPipelineId: string = '';
  private abortController: AbortController | null = null;

  private emitEvent(eventType: any, message: string, data?: any): void {
    const event: IPipelineEvent = {
      eventId: crypto.randomUUID ? crypto.randomUUID() : `event-${Date.now()}`,
      eventType,
      timestamp: Date.now(),
      state: this.state,
      message,
      data
    };
    pipelineEventBus.emit(event);
  }

  public getState(): PipelineState {
    return this.state;
  }

  public stop(): void {
    if (this.abortController) {
      this.abortController.abort();
      this.state = 'CANCELLED';
      this.emitEvent('PipelineFailed', 'Pipeline execution stopped by user.');
    }
  }

  public async run(
    rawPrompt: string,
    workspacePath?: string,
    provider?: IPlanningModelProvider,
    codingProvider?: ICodingModelProvider,
    fsAdapter?: IFilesystemAdapter
  ): Promise<IPipelineResult> {
    const startTime = Date.now();
    this.currentPipelineId = crypto.randomUUID ? crypto.randomUUID() : `pipeline-${Date.now()}`;
    this.abortController = new AbortController();

    this.state = 'PROCESSING_PROMPT';
    this.emitEvent('PromptReceived', `Processing user prompt of length ${rawPrompt.length}`);

    const errors: string[] = [];
    const warnings: string[] = [];
    let devRequest: any = null;
    let generationResult: any = null;
    let workspaceReport: any = null;

    console.log('[TRACE] [Prompt Engine] ENTER: Prompt received:', rawPrompt.substring(0, 60));
    try {
      // Execute through AI Kernel (Single Entry Point for all user prompts)
      // Calls Context Builder, Memory Engine, Knowledge Engine, and Model Router
      const compiledKernelRequest = await aiKernel.processPrompt({
        rawPrompt,
        workspacePath,
        provider,
        codingProvider,
        fsAdapter
      }, workspacePath);

      this.emitEvent('PromptParsed', 'Prompt successfully compiled through AI Kernel runtime stages.');

      if (this.abortController.signal.aborted) {
        throw new Error('Pipeline cancelled.');
      }

      const aiRequest = compiledKernelRequest.aiRequest;

      // Extract results from Orchestrator Workflow
      this.state = 'PLANNING';
      this.emitEvent('PlanningStarted', 'Formulating AI planning session instructions and guidelines.');
      this.emitEvent('PlanningCompleted', 'Planning Contract generated by model.');

      this.state = 'VALIDATING_PLAN';
      this.emitEvent('ValidationStarted', 'Validating tasks dependencies and checking command injections safety.');
      this.emitEvent('ValidationCompleted', 'Safety checks and schema validations completed.');

      this.state = 'PREPARING_DEVELOPMENT';
      this.emitEvent('DevelopmentRequestCreated', 'Development Request is formulated and ready for code execution.');

      this.state = 'GENERATING_CODE';
      this.emitEvent('GeneratorSessionCreated', 'Generator Session initialized for module generation plans.');
      this.emitEvent('CodingRuntimeInvoked', 'Invoking Coding Model runtime client.');
      this.emitEvent('LLMResponseReceived', 'LLM Response stream received successfully.');

      this.emitEvent('GenerationStarted', 'Code generation started via Orchestrator Agent Workflow.');
      
      const orchestrationResult = compiledKernelRequest.orchestrationResult;
      if (!orchestrationResult || orchestrationResult.status !== 'SUCCESS') {
        throw new Error(`Orchestration failed: ${orchestrationResult?.errors?.join(', ') || 'Unknown error'}`);
      }

      this.emitEvent('OllamaRequest', 'Sending code generation request to Ollama.');

      const executorTask = orchestrationResult.agentResults.find((r: any) => r.agentId === 'executor-agent' && r.success);
      if (!executorTask) {
        throw new Error('Executor Agent task did not execute successfully.');
      }

      this.emitEvent('OllamaResponse', 'Received code response from Ollama.');

      generationResult = executorTask.result.generationResult;
      workspaceReport = executorTask.result.workspaceReport;

      this.emitEvent('GenerationContractCreated', `Generation Contracts created for all modules.`);
      
      this.state = 'APPLYING_CHANGES';
      this.emitEvent('WorkspaceEngineStarted', 'Workspace Engine executing atomic file operations.');
      this.emitEvent('FilesGenerated', `Files successfully written: ${workspaceReport.createdFiles.join(', ')}`);
      
      console.log('[TRACE] [Review Changes] ENTER: Refreshing visual diff panel');
      this.emitEvent('ReviewChangesUpdated', 'Review Changes dashboard populated with generated code and diff preview.');
      console.log('[TRACE] [Review Changes] EXIT: Visual diff panel refreshed');

      this.state = 'SUCCESS';
      this.emitEvent('PipelineCompleted', 'AI Planning & Generation Pipeline finished successfully.');
      console.log('[TRACE] [Prompt Engine] EXIT: Pipeline completed successfully');
    } catch (err: any) {
      if ((this.state as string) !== 'CANCELLED') {
        this.state = 'FAILED';
      }
      errors.push(err.message || String(err));
      this.emitEvent('PipelineFailed', `Pipeline failed with error: ${err.message}`);
      console.log('[TRACE] [Prompt Engine] EXIT with error:', err.message);
    }

    const duration = Date.now() - startTime;

    return {
      pipelineId: this.currentPipelineId,
      state: this.state,
      developmentRequest: devRequest,
      executionTimeMs: duration,
      warnings: Object.freeze(warnings),
      errors: Object.freeze(errors),
      generationResult,
      workspaceReport
    };
  }
}

export const pipelineController = new PipelineController();
export default pipelineController;
