export enum SessionEventType {
  SESSION_CREATED = 'SESSION_CREATED',
  SESSION_UPDATED = 'SESSION_UPDATED',
  SESSION_SWITCHED = 'SESSION_SWITCHED',
  SESSION_CLOSED = 'SESSION_CLOSED',
  SESSION_DELETED = 'SESSION_DELETED',
  SESSION_RENAMED = 'SESSION_RENAMED'
}
