export enum ActionType {
  READ_FILE = 'READ_FILE',
  WRITE_FILE = 'WRITE_FILE',
  CREATE_FILE = 'CREATE_FILE',
  DELETE_FILE = 'DELETE_FILE',
  RENAME_FILE = 'RENAME_FILE',
  RUN_COMMAND = 'RUN_COMMAND',
  INSTALL_PACKAGE = 'INSTALL_PACKAGE',
  UPDATE_CONFIGURATION = 'UPDATE_CONFIGURATION',
  UNKNOWN = 'UNKNOWN'
}
