export enum PlanStatus {
  CREATED = 'CREATED',
  ANALYZING = 'ANALYZING',
  READY = 'READY',
  WAITING_APPROVAL = 'WAITING_APPROVAL',
  EXECUTING = 'EXECUTING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED'
}
