import { BaseGenerator } from './baseGenerator';
import { GeneratedFile, GenerationContext, GenerationStrategy } from '../generationTypes';

export class MockGenerator extends BaseGenerator {
  public async generate(
    context: GenerationContext,
    strategy: GenerationStrategy,
    plan: any
  ): Promise<GeneratedFile[]> {
    const fileExtension = context.language === 'typescript' ? 'ts' : 'js';
    const primaryName = plan.title ? plan.title.replace(/\s+/g, '') : 'GeneratedFeature';
    const filePath = `${context.targetPath}/${primaryName.toLowerCase()}.${fileExtension}`;

    let content = '';
    const symbols = [
      { name: primaryName, type: 'class' as const },
      { name: 'executeAction', type: 'function' as const }
    ];

    if (strategy === GenerationStrategy.CreateNewFeature || strategy === GenerationStrategy.Scaffold) {
      content = `/**
 * Generated by Code Generation Engine
 * Strategy: ${strategy}
 */
export class ${primaryName} {
  constructor() {
    console.log('${primaryName} initialized.');
  }

  public executeAction(input: string): string {
    return 'Result: ' + input;
  }
}
`;
    } else {
      content = `/**
 * Generated Modification Code
 * Strategy: ${strategy}
 */
export function executeAction(data: any) {
  return data;
}
`;
    }

    return [{
      path: filePath,
      content,
      symbols
    }];
  }
}

export const mockGenerator = new MockGenerator();
